version: '2'

services:
  memcache:
    container_name: memcache
    image: memcached:1.4.25

  logjamdb:
    container_name: logjamdb
    image: mongo:3.0.12

  demo:
    container_name: logjam-demo
    image: stkaes/logjam-app
    ports:
      - "80:80"
      - "8080:8080"
      - "9605:9605"
      - "9705:9705"
    tty: true
    environment:
      - LOGJAMDB_NAME=logjamdb
      - MEMCACHE_NAME=memcache
    env_file:
      - "logjam.env"
